# Generated by Django 4.2.5 on 2023-09-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=60)),
                ('clothe', models.CharField(max_length=40)),
                ('date', models.DateField(max_length=10)),
                ('gender', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('document', models.FileField(upload_to='uploads/')),
                ('photo', models.ImageField(default=None, null=True, upload_to='images/')),
            ],
        ),
    ]
